language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
install:
  - composer install --optimize-autoloader
  - chmod +x ./primi ./bin/*
script:
  - ./bin/test
after_script:
  - ./bin/phpstan
  - ./bin/bench
