language: php
php:
  - '7.0'
  - '7.1'
  - nightly
install:
- composer install --optimize-autoloader
- chmod +x ./primi ./bin/runtests ./bin/runsmoketests
script:
- ./bin/runsmoketests
- ./bin/runtests
